channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pip>=22.3
  - click
  - boto3
  - eccodes>=2.25.0,<2.34
  - earthkit-data>=0.2.0
  - jinja2>=3.1.1
  - numpy>=1.23
  - python-eccodes>=1.5.1
  - xarray>=2023.4.1