apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flexpart_ifs-main-devt

resources:
  - ../../base

images:
  - name: docker-all-nexus.meteoswiss.ch/flexpart_ifs/flexprep
    newTag: flexpart_ifs-devt

patchesStrategicMerge:
  - configmap.yaml
