apiVersion: batch/v1
kind: Job
metadata:
  name: pilotecmwf_pp_starter
spec:
  ttlSecondsAfterFinished: 1800
  template:
    spec:
      containers:
        - name: pilotecmwf_pp_starter
          image: docker-all-nexus.meteoswiss.ch/flexpart_ifs/pilotecmwf_pp_starter
          imagePullPolicy: Always
          env:
            - name: LOGGING__ROOT_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: pilotecmwf_pp_starter-settings
                  key: logging_level
            - name: LOGGING__FORMATTER
              valueFrom:
                configMapKeyRef:
                  name: pilotecmwf_pp_starter-settings
                  key: logging_formatter
          resources:
            limits:
              cpu: "3"
              memory: 128Mi
            requests:
              cpu: 20m
              memory: 128Mi
      automountServiceAccountToken: false
      restartPolicy: Never
