apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flexpart_ifs-main-depl

resources:
  - ../../base

images:
  - name: docker-all-nexus.meteoswiss.ch/flexpart_ifs/pilotecmwf_pp_starter
    newTag: flexpart_ifs-depl
